config/routes.rb
IntegratedAnalysis::Application.routes.draw do
  devise_for :admins
  devise_for :users
  match "welcome/index", :via => [:get, :post]
  get "welcome/login"

  root 'properties#index'
  post "welcome/search"
  resources :properties do
    collection do
      get "send_query"
      get "get_in_touch"
    end
  end

end

app/models/property.rb
class Property < ActiveRecord::Base

  belongs_to :user
  scope :size_between,lambda {|from,to| {:conditions => ["Property.size between ? and ?",from,to]}}
  scope :price_between,lambda {|from,to| {:conditions => ["price between ? and ?",from,to]}}
  mount_uploader :image, ImageUploader
  validates :project,:city, :area, :size, :contact, :price, :presence => true

  TODO_TYPE = {
    "Rent" => "0",
    "Sale" => "1"
  }
  PROPERTY_TYPE = {
    "Original Booking" => "0",
    "Multistorey Apartment"  => "1",
    "Builder Floor Apartment" => "2",
    "Residential House" => "3",
    "Villa" => "4",
    "Residential Plot" => "5",
    "Penthouse" => "6",
    "Studio Apartment" => "7",
    "Service Apartment" => "8",
    "Holiday Home" => "9",
    "Commercial Office Space" => "10",
    "Office in IT Park/ SEZ" => "11",
    "Commercial Shop" => "12",
    "Space in Shopping Mall" => "13",
    "Commercial Showroom" => "14",
    "Kiosk" => "15",
    "Business Centre" => "16",
    "Commercial Land" => "17",
    "Warehouse/ Godown" => "18",
    "Guest House" => "19",
    "Hotel" => "20",
    "Hotel Sites" => "21",
    "Industrial Land" => "22",
    "Industrial Building" => "23",
    "Industrial Shed" => "24"
  }

  PROFESSIONAL_TYPE = {
    "Ready to move" => "0",
    "Under Construction" => "1",
  }

  LISTING_AMENITIES = ["Parking","Garden","Gym","Lift","Power Backup","Swimming Pool","Security","Balcony"]

  BUILDING_AMENITIES = ["Rain Water Harvesting","Club House","Covered Parking","Vastu","Tiled Flooring","Terrace","Servant Quarters","Intercom","Jacuzzi","Basement","Sauna","Air Conditioned"]

  PRICING_TEXT = {
    "Lacs" => "0",
    "Crores" => "1",
    "per month (if rent)" => "2"
  }

  CITIES = {
    "Gurgaon" => "Gurgaon",
    "Mumbai" => "Mumbai",
    "Bangalore" => "Bangalore",
    "Chennai" => "Chennai",
    "Hyderabad" => "Hyderabad",
    "Pune" => "Pune",
    "Kolkata" => "Kolkata",
    "Jaipur" => "Jaipur",
    "Goa" => "Goa",
    "Lucknow" => "Lucknow",
    "Ahemdabad" => "Ahemdabad",
    "Surat" => "Surat"
  }

  self.per_page = 10

  def self.search_data(search)
  	lc = ActiveSupport::OrderedHash.new
    lc[:min_sqrt] = []
    lc[:max_sqrt] = []
    lc[:min_price] = []
    lc[:max_price] = []
    lc[:to_do] =[]
    scope = Property.all
    if search && !search[:min_sqrt].blank? && !search[:max_sqrt].blank?
      scope = scope.select{|x| x.size.to_f >= search[:min_sqrt].to_f && x.size.to_f <= search[:max_sqrt].to_f}
    elsif search && !search[:min_sqrt].blank? && search[:max_sqrt].blank?
      scope = scope.select{|x| x.size.to_f >= search[:min_sqrt].to_f}
    elsif search && !search[:max_sqrt].blank? && search[:min_sqrt].blank?
      scope = scope.select{|x| x.size.to_f <= search[:max_sqrt].to_f}
    end
    if search && !search[:min_price].blank? && !search[:max_price].blank?
    	scope = scope.select{|x| x.size.to_f >= search[:min_price].to_f && x.size.to_f <= search[:max_price].to_f}
    elsif search && !search[:min_price].blank? && search[:max_price].blank?
      scope = scope.select{|x| x.size.to_f >= search[:min_price].to_f}
    elsif search && search[:min_price].blank? && !search[:max_price].blank?
      scope = scope.select{|x| x.size.to_f <= search[:max_price].to_f}
    end
    if search && !search[:to_do].blank?
      scope = scope.select{|x| x.to_do == search[:to_do].to_i}
    end
    if search && !search[:city].blank?
      scope = scope.select{|x| x.city == search[:city]}
    end
    scope
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  
  layout 'new_layout', :only => [:login]
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @user = current_user
    if params[:search].present?
      @properties = Property.search_data(params[:search])
    else
      @properties = Property.all.paginate(:page => params[:page], :per_page => 10)
    end
  end

  def login
  end

  def search
    @properties = Property.properties.search_data(params[:search]).paginate(:page => params[:page], :per_page => 10)
    redirected_to welcome_search_path(params.merge(params[:search]))
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  def send_query
  end

  def get_in_touch
    
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = current_user.properties.build(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to welcome_index_path, notice: 'Property was successfully created.' }
        format.json { render action: 'show', status: :created, location: @property }
      else
        format.html { render action: 'new' }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to welcome_index_path, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:photo, :project, :area, :city, :posted_at, :price, :size, :to_do,
       :contact, :professional_type, :data_available, :amenities, :name, :company,
       :email, :phone, :price_text, :comment_title, :comments, :floor,:image)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_contact_form.html.erb
<div class="col-md-4">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 style="margin-top:0px;">Intrested?</h3><h3 class="panel-title">Get in Touch with the owner</h3>
    </div>
    <div class="panel-body">

      <%= form_tag(send_query_properties_path, {:method => :get, :class => "form form-horizontal"}) do %>
        <div class="form-group">
          <div class="col-md-12"><%= text_field_tag "email", params[:email], :class => "form-control", :placeholder => "Email" %></div>
        </div>
        <div class="form-group">
          <div class="col-md-12"><%= text_field_tag "name", params[:name], :class => "form-control", :placeholder => "Name" %></div>
        </div>
        <div class="form-group">
          <div class="col-md-12"><%= text_field_tag "phone", params[:phone], :placeholder => "Mobile No.", :class => "form-control datetime" %></div>
        </div>
        <div class="form-actions form-actions-padding-sm">
          <div class="row">
            <div class="col-md-12">
              <%= submit_tag "Send Message",id: "do_migration", :class => "pull-right btn btn-warning" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/properties/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="box">
      <div class="box-header">
        <h2>
          <i class="icon-edit"></i>
          Post Your Listing
        </h2>
        <div class="box-icon">
          <a class="btn-setting" href="form-elements.html#"><i class="icon-wrench"></i></a>
          <a class="btn-minimize" href="form-elements.html#"><i class="icon-chevron-up"></i></a>
          <a class="btn-close" href="form-elements.html#"><i class="icon-remove"></i></a>
        </div>
      </div>
      <div class="box-content">
        <%= simple_form_for(@property,:html => {:style => "border: 1px solid #D9D9D9; padding: 30px;"})  do |f|  %>
          <% if @property.errors.any? %>
            <div id="error_explanation">
              <h2 style="margin-top:0px;margin-bottom:30px;"><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>
            </div>
          <% end %>
          <fieldset>
            <div class="col-sm-2">
              <div class="lead text-muted">
                <i class="icon-github text-muted"></i>
                Project Detail
              </div>
            </div>
            <div class="col-sm-5">
              <%= f.input :project %>
              <%= f.input :city %>
              <div class="col-sm-3"><%= f.label :size %></div>
              <div class="input-group col-sm-9 " style="margin-left: 20px;">
                <%= f.text_field :size, :class => "form-control" %>
                <span class="input-group-addon">sqrt</span>
              </div>
              <div style="margin-top: 60px;"></div>
              <%= f.input :contact %>
            </div>
            <div class="col-sm-5">
              <%= f.input :area %>
              <%= f.input :floor %>
              <%= f.input(:to_do, :collection => Property::TODO_TYPE, :include_blank => false) %>
            </div>
          </fieldset>
          <hr class="hr-normal">
          <fieldset>
            <div class="col-sm-2">
              <div class="lead text-muted">
                <i class="icon-github text-muted"></i>
                Project Image
              </div>
            </div>
            <div class="col-sm-10">
              <%= f.file_field :image, label: "Upload Image" %>
            </div>
          </fieldset>
          <hr class="hr-normal">
          <fieldset>
            <div class="col-sm-2">
              <div class="lead text-muted">
                <i class="icon-github text-muted"></i>
                Address
              </div>
            </div>
            <div class="col-sm-10">
              <%= f.input :address_line_1 %>
              <%= f.input :address_line_2 %>
            </div>
          </fieldset>
          <hr class="hr-normal">
          <fieldset>
            <div class="col-sm-2">
              <div class="lead text-muted">
                <i class="icon-money text-contrast"></i>
                Pricing Detail
              </div>
            </div>
            <div class="col-sm-10">
              <div class="col-sm-2"><%= f.label :price %></div>
              <div class="input-group color col-sm-10" style="margin-left: -12px;">
                <span class="input-group-addon">Rs</span>
                <%= f.text_field :price, :class => "form-control" %>
                <span class="input-group-addon">
                  <%= f.input_field(:price_text, :collection => Property::PRICING_TEXT, :include_blank => false) %>
                </span>
              </div>
              <div style="margin-top: 50px;"></div>
              <%= f.input :professional_type, :collection => Property::PROFESSIONAL_TYPE, :include_blank => false %>
              <%= f.input :data_available %>
            </div>
          </fieldset>
          <hr class="hr-normal">
          <fieldset>
            <div class="col-sm-4">
              <div class="lead text-muted">
                <i class="icon-money text-contrast"></i>
                Amenities
              </div>
            </div>
            <div class="col-sm-4">
              <label class="control-label">Listing amenities</label>
              <div class="controls">
                <%= hidden_field_tag "listing_amenities[]", nil %>
                <% Property::LISTING_AMENITIES.each_with_index do |l,n| %>
                  <label class = "checkbox inline">
                    <%= check_box_tag "listing_amenities[]", n+1, :id => "listing_amenties_#{n+1}" %>
                    <%= label_tag "listing_amenties_#{n+1}",l, :class => "control-label label-class" %>
                  </label>
                <% end %>
              </div>
            </div>
            <div class="col-sm-4">
              <label class="control-label">Building amenities</label>
              <div class="controls">
                <%= hidden_field_tag "listing_amenities[]", nil %>
                <% Property::BUILDING_AMENITIES.each_with_index do |l,n| %>
                  <label class = "checkbox inline">
                    <%= check_box_tag "listing_amenities[]", n+1, :id => "listing_amenties_#{n+1}" %>
                    <%= label_tag "listing_amenties_#{n+1}",l, :class => "control-label label-class" %>
                  </label>
                <% end %>
              </div>
            </div>
          </fieldset>
          <hr class="hr-normal">
          <fieldset>
            <div class="col-sm-2">
              <div class="lead text-muted">
                <i class="icon-comment text-contrast"></i>
                Comments
              </div>
            </div>
            <div class="col-sm-10">
              <%= f.input :comment_title %>
              <%= f.input :comments, :rows => "7", :cols=> "11" %>
            </div>
          </fieldset>
          <div class="form-actions">
            <div class="row">
              <div class="col-sm-7 col-sm-offset-4">
                <%= button_tag(type: 'submit', class: "btn btn-success btn-lg") do %>
                  <i class="icon-save icon-white"></i> Submit Listing
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/properties/_get_in_touch.html.erb
<%= form_tag(get_in_touch_properties_path(params[:search]), :method => :post, :class => "form form-horizontal") do %>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group">
        <div class="col-md-2">
          <%= label_tag "message", "Message", :class => "control-label label-class" %>
        </div>
        <div class="col-md-9">
          <%= text_area_tag("search[area]", (params[:search] && params[:search][:area]), :class => "form-control", :placeholder=> "Message Upto 120 words") %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-2">
          <%= label_tag "email", "Email", :class => "control-label label-class" %>
        </div>  
        <div class="col-md-4">
          <%= text_field_tag("search[email]", (params[:search] && params[:search][:email]), :class => "form-control", :placeholder=> "email") %>
        </div>
        <div class="col-md-1">
          <%= label_tag "mobil", "Mobile", :class => "control-label label-class" %>
        </div>  
        <div class="col-md-4">
          <%= text_field_tag("search[mobile]", (params[:search] && params[:search][:mobile]), :class => "form-control", :placeholder=> "mobile") %>
        </div>
      </div>
      <div class="form-group">  
        <div class="col-md-2"></div> 
        <div class="col-md-2">
          <button type="submit" class="btn btn-success"><i class="icon-search"></i> Submit</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/properties/_premium.html.erb
<div class="col-md-4">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Premium Propeties</h3>
    </div>
    <div class="panel-body">
      <h5><span class="text-muted"><%= "#{@property.project} for #{Property::TODO_TYPE.keys[@property.to_do]} at #{@property.area} "%></span></h5>
      <div class="col-md-6">
        <%= image_tag("/images/yes.jpg", size: "150x100") %>
      </div>
      <div class="col-md-6">
        <strong><%="#{@property.price} Lacs" %></strong>
        <p class="text-muted"><small>By:- Arvind Mehra <em>(Broker)</em></small>
          <span><small>Listed on <%=@property.created_at.to_date %></small></span>
        </p>
      </div>
    </div>
    <div class="panel-body">
      <h5><span class="text-muted"><%= "#{@property.project} for #{Property::TODO_TYPE.keys[@property.to_do]} at #{@property.area} "%></span></h5>
      <div class="col-md-6">
        <%= image_tag("/images/yes.jpg", size: "150x100") %>
      </div>
      <div class="col-md-6">
        <strong><%="#{@property.price} Lacs" %></strong>
        <p class="text-muted"><small>By:- Arvind Mehra <em>(Broker)</em></small>
          <span><small>Listed on <%=@property.created_at.to_date %></small></span>
        </p>
      </div>
    </div>
    <div class="panel-body">
      <h5><span class="text-muted"><%= "#{@property.project} for #{Property::TODO_TYPE.keys[@property.to_do]} at #{@property.area} "%></span></h5>
      <div class="col-md-6">
        <%= image_tag("/images/yes.jpg", size: "150x100") %>
      </div>
      <div class="col-md-6">
        <strong><%="#{@property.price} Lacs" %></strong>
        <p class="text-muted"><small>By:- Arvind Mehra <em>(Broker)</em></small>
          <span><small>Listed on <%=@property.created_at.to_date %></small></span>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/properties/_search_area.html.erb
      <div class="row">
        <div class="col-lg-12">
          <section class="panel" style="border: 1px solid #D9D9D9;">
            <div class="panel-body">
              <%= form_tag(properties_path(params[:search]), :method => :post, :class => "form form-horizontal") do %>
                <div class="row">
                  <div class="col-sm-12">
                    <div class="col-sm-2">
                      <%= select_tag "search[city]",options_for_select(Property::CITIES,(params[:search] && params[:search][:city])), :class => "area-width" %>
                    </div>
                    <div class="col-sm-2">
                      <%= select_tag "search[to_do]",options_for_select(Property::TODO_TYPE,(params[:search] && params[:search][:to_do])), :class => "area-width" %>
                    </div>
                    <div class="col-sm-3">
                      <%= select_tag "search[property_type]",options_for_select(Property::PROPERTY_TYPE,(params[:search] && params[:search][:property_type])), :class => "area-width" %>
                    </div>
                    <div class="col-sm-4">
                      <div class="col-sm-6">
                        <%= text_field_tag("search[min_price]", (params[:search] && params[:search][:min_price]), :class => "form-control", :placeholder=> "Min price") %>
                      </div>
                      <div class="col-sm-6">
                        <%= text_field_tag("search[max_price]", (params[:search] && params[:search][:max_price]), :class => "form-control", :placeholder=> "Max price") %>
                      </div>
                    </div>
                    <div class="col-sm-1">
                      <button type="submit" class="btn btn-success"><i class="icon-search"></i> Search</button>
                    </div>
                  </div>
                </div>
              <% end %>
              <h4><i class="icon-user"></i><span class="break"></s<pan><%= Property.all.size %> office spaces for rent </h4>
            </div>
          </section>
        </div>
      </div>

app/views/properties/edit.html.erb
<%= render 'form' %>

app/views/properties/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="box">
      <%= render 'search_area' %>
      <div class="col-md-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Popular Properties</h3>
            </div>
            <div class="panel-body">
              <table class="table borderless">
                <% @properties.each do |p| %>
                  <tr>
                    <td style="border-bottom: 1px solid #eeeeee; ">
                      <span class="glyphicon glyphicon-hand-right action-buttons"></span>
                      <%= link_to("#{p.area} : #{p.project}, Address Line, #{p.price} lacs", property_path(p.id)) %>
                    </td>
                  </tr>
              <% end %>    
              </table>
          </div>
        </div>
      </div>


      <div class="col-md-9">
        <% @properties.each do |property| %>
          <div class="bs-callout bs-callout-warning col-md-12">
            <div class="col-md-4">
              <%= link_to(image_tag("/images/yes.jpg", size: "250x150"), property_path(property.id)) %>
            </div>
            <div class="col-md-4" >
              <h4><%= link_to(property.project, property_path(property.id)) %></h4>
              <p><%="#{property.area}, #{property.city}"%></p>
              <p style="margin:0px;">1/2/3 BHK Independent Flat</p>
              <p><%= "Price Starts @ #{property.price} lacs onward" %></p>
              <p><span class=" btn btn-warning">
                <%= link_to("View Contact", property_path(property.id),style: "color:#fff") %></span>
              </p>
            </div>
            <div class="col-md-4 ">
              <p class="pull-right" ><%="Call: +91-#{property.contact}"%></p>

              <p class="pull-right"><span class=" btn btn-info">
                <%= link_to("Get in Touch", "##{property.id}",:"data-toggle"=>"collapse", :"data-parent"=>"#accordion",style: "color:#fff") %></span>
              </p>  
            </div>
            <div class="col-md-12" id="accordion">
              <div id=<%="#{property.id}"%> class="panel-collapse collapse">
              <div class="panel-body">
                <%= render 'get_in_touch' %>
              </div>
            </div>
            </div>  
          </div>
        <% end %>
        <%= will_paginate @properties, renderer: BootstrapPagination::Rails  unless params[:search].present? %>
      </div>
    </div>
  </div><!--/col-->

</div><!--/row-->

app/views/properties/new.html.erb
<%= render 'form' %>

app/views/properties/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12" style="margin-left:20px"><h3><%= "#{@property.project} for #{Property::TODO_TYPE.keys[@property.to_do]} at #{@property.area} "%></h3>
      <span><h4>Sector-5, Rambagh</h4></span>
    </div>
    <div class="col-md-8" style="padding-top:15px; border-top: 1px solid #428bca;">
      <div class="col-md-6"><img src="/images/yes.jpg"></div>
      <div class="col-md-6">
        <span class="col-md-4"><h4 style="margin-bottom:0px">3BHK</h4><small class="type-info">For Sale</small></span>
        <span class="col-md-4"><h4 style="margin-bottom:0px"><%="#{@property.price} Lacs" %></h4>
          <small class="type-info">Negotiable</small>
        </span>
        <span class="col-md-4"><h4 style="margin-bottom:0px"><%=@property.size %></h4>
          <small class="type-info">Sq. Ft</small>
        </span>
        <table class="table">
          <tr>
            <td><strong>Type of Property</strong></td>
            <td>Apartment</td>
          </tr>
          <tr>
            <td><strong>Project Name</strong></td>
            <td><%=@property.project%></td>
          </tr>
          <tr>
            <td><strong>Locality</strong></td>
            <td><%=@property.area%></td>
          </tr>
          <tr>
            <td><strong>City</strong></td>
            <td><%=@property.city%></td>
          </tr>
          <tr>
            <td><strong>Type</strong></td>
            <td><span class="label label-primary"><%= Property::TODO_TYPE.keys[@property.to_do] if  @property.to_do %></span></td>
          </tr>
          <tr>
            <td><strong>Flooring</strong></td>
            <td>Wooden</td>
          </tr>
          <tr>
            <td><strong>Carpet Area</strong></td>
            <td>1900 Sq.ft</td>
          </tr>
        </table>
      </div>
      <div class="col-md-12">
        <div class="well well-lg">
          Property Posted By:- <strong>Amit Surolia</strong>&nbsp<em>(owner)</em>
          <span class="pull-right" ><%="Call: +91-#{@property.contact}"%></span>
        </div>
        <h4>Location Details</h4>
        <div class="col-md-6">
          <table class="table borderless">
            <tr>
              <td style="border:none"><strong>Address</strong></td>
              <td style="border:none">Janta Colony, Near Ghat Gate</td>
            </tr>
            <tr>
              <td style="border:none"><strong>City</strong></td>
              <td style="border:none"><%=@property.city%></td>
            </tr>
            <tr>
          </table>
        </div>  
      </div>
    </div>
    <%= render "contact_form" %>
    <%= render "premium" %>
  </div>
</div>