config/routes.rb
IntegratedAnalysis::Application.routes.draw do
  devise_for :admins
  devise_for :users
  match "welcome/index", :via => [:get, :post]
  get "welcome/login"

  root 'properties#index'
  post "welcome/search"
  resources :properties do
    collection do
      get "send_query"
      get "get_in_touch"
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  layout 'new_layout', :only => [:login]

  def index
    @user = current_user
    if params[:search].present?
      @properties = Property.search_data(params[:search])
    else
      @properties = Property.all.paginate(:page => params[:page], :per_page => 10)
    end
  end

  def login
  end

  def search
    @properties = Property.properties.search_data(params[:search]).paginate(:page => params[:page], :per_page => 10)
    redirected_to welcome_search_path(params.merge(params[:search]))
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="box">
      <div class="row">
        <div class="col-lg-12">
          <section class="panel" style="border: 1px solid #D9D9D9;">
            <div class="panel-body">
              <%= form_tag(welcome_index_path(params[:search]), :method => :post, :class => "form form-horizontal") do %>
                <div class="row">
                  <div class="col-sm-12">
                    <div class="col-sm-2">
                      <%= select_tag "search[city]",options_for_select(Property::CITIES,(params[:search] && params[:search][:city])), :class => "area-width" %>
                    </div>
                    <div class="col-sm-2">
                      <%= select_tag "search[to_do]",options_for_select(Property::TODO_TYPE,(params[:search] && params[:search][:to_do])), :class => "area-width" %>
                    </div>
                    <div class="col-sm-3">
                      <%= select_tag "search[property_type]",options_for_select(Property::PROPERTY_TYPE,(params[:search] && params[:search][:property_type])), :class => "area-width" %>
                    </div>
                    <div class="col-sm-4">
                      <div class="col-sm-6">
                        <%= text_field_tag("search[min_price]", (params[:search] && params[:search][:min_price]), :class => "form-control", :placeholder=> "Min price") %>
                      </div>
                      <div class="col-sm-6">
                        <%= text_field_tag("search[max_price]", (params[:search] && params[:search][:max_price]), :class => "form-control", :placeholder=> "Max price") %>
                      </div>
                    </div>
                    <div class="col-sm-1">
                      <button type="submit" class="btn btn-success"><i class="icon-search"></i> Search</button>
                    </div>
                  </div>
                </div>
              <% end %>
              <h4><i class="icon-user"></i><span class="break"></s<pan><%= Property.all.size %> office spaces for rent </h4>
            </div>
          </section>
        </div>
      </div>
      <div id="property-table" class="box-content">
        <table class="table table-striped table-bordered bootstrap-datatable datatable">
          <thead>
            <tr>
              <th>ID</th>
              <th>Photo</th>
              <th>Project</th>
              <th>Area</th>
              <th>City</th>
              <th>Posted</th>
              <th>Price<span class="text-muted"> (Rs)</span></th>
              <th>Size<span class="text-muted"> (sqrt)</span></th>
              <th>For sale/buy/rent</th>
              <th>Contact</th>
            </tr>
          </thead>
          <tbody>
            <% @properties.each do |property| %>
              <tr>
                <td><%= property.id %></td>
                <td><img src="<%= property.image %>" style="height: 23px; width: 23px;"> x 3</td>
                <td><%= link_to(property.project, edit_property_path(property.id)) %></td>
                <td><%= property.area %></td>
                <td><%= property.city %></td>
                <td><%= property.created_at.to_s(:short) %></td>
                <td><%= property.price %></td>
                <td><%= property.size %></td>
                <td><span class="label label-primary"><%= Property::TODO_TYPE.keys[property.to_do] if  property.to_do %></span></td>
                <td><%= property.contact %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @properties, renderer: BootstrapPagination::Rails  unless params[:search].present? %>
      </div>
    </div>
  </div><!--/col-->

</div><!--/row-->

app/views/welcome/login.html.erb
<div class="row">
	<div class="login-box">
		<h2>Login to your account</h2>
		<form class="form-horizontal" action="index.html" method="post">
			<fieldset>

				<input class="input-large col-xs-12" name="username" id="username" type="text" placeholder="type username"/>

				<input class="input-large col-xs-12" name="password" id="password" type="password" placeholder="type password"/>

				<div class="clearfix"></div>

				<label class="remember" for="remember"><input type="checkbox" id="remember" />Remember me</label>

				<div class="clearfix"></div>

				<button type="submit" class="btn btn-primary col-xs-12">Login</button>
			</fieldset>

		</form>
		<hr>
		<h3>Forgot Password?</h3>
		<p>
			No problem, <a href="login.html#">click here</a> to get a new password.
		</p>
	</div>
</div><!--/row-->