config/routes.rb
IntegratedAnalysis::Application.routes.draw do
  devise_for :admins
  devise_for :users
  match "welcome/index", :via => [:get, :post]
  get "welcome/login"

  root 'properties#index'
  post "welcome/search"
  resources :properties do
    collection do
      get "send_query"
      get "get_in_touch"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- start: Meta -->
  <meta charset="utf-8">
  <title>Integrated Analysis</title>
  <!-- start: Mobile Specific -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- end: Mobile Specific -->

  <!-- start: CSS -->
  <%= stylesheet_link_tag 'application', media: "all" %>
  <%= javascript_include_tag "application" %>
  <!-- end: CSS -->
  <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
     <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <script src="assets/js/respond.min.js"></script>
    <script src="assets/css/ie6-8.css"></script>
  <![endif]-->
</head>
<body>
  <div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="navbar-header">
      <%= link_to("Integrated Analysis",root_path,:class => "navbar-brand") %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to("Gurgaon","#",:style => "float: left;font-size: 14px;height: 50px;line-height: 20px;padding: 15px;") %></li>
        <li><%= link_to("Mumbai","#",:style => "float: left;font-size: 14px;height: 50px;line-height: 20px;padding: 15px;") %></li>
        <li><%= link_to("Bangalore","#",:style => "float: left;font-size: 14px;height: 50px;line-height: 20px;padding: 15px;") %></li>
        <li><%= link_to("Chennai","#",:style => "float: left;font-size: 14px;height: 50px;line-height: 20px;padding: 15px;") %></li>
        <li><%= link_to("Hyderabad","#",:style => "float: left;font-size: 14px;height: 50px;line-height: 20px;padding: 15px;") %></li>
        <li><%= link_to("Pune","#",:style => "float: left;font-size: 14px;height: 50px;line-height: 20px;padding: 15px;") %></li>
        <li><%= link_to("Kolkata","#",:style => "float: left;font-size: 14px;height: 50px;line-height: 20px;padding: 15px;") %></li>
        <li class="dropdown">
          <%= link_to("More <b class='caret'></b>".html_safe, "#", :class=> "dropdown-toggle", :'data-toggle' => "dropdown") %>
          <ul class="dropdown-menu">
            <li><%= link_to("Jaipur","#",:style => "float: left;font-size: 14px;height: 50px;line-height: 20px;padding: 15px;") %></li>
            <li><%= link_to("Goa","#",:style => "float: left;font-size: 14px;height: 50px;line-height: 20px;padding: 15px;") %></li>
            <li><%= link_to("Lucknow","#",:style => "float: left;font-size: 14px;height: 50px;line-height: 20px;padding: 15px;") %></li>
            <li><%= link_to("Surat","#",:style => "float: left;font-size: 14px;height: 50px;line-height: 20px;padding: 15px;") %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <li class="dropdown">
            <%= link_to("#{current_user.email} <b class='caret'></b>".html_safe, "#", :class=> "dropdown-toggle", :'data-toggle' => "dropdown") %>
            <ul class="dropdown-menu">
              <li><%= link_to("<i class='icon-home'></i> Home".html_safe,root_path) %></li>
              <li><%= link_to("<i class='icon-plus-sign'></i> Add New Property".html_safe,new_property_path,:style => "float: left;font-size: 14px;height: 50px;line-height: 20px;padding: 15px;") %></li>
              <li><%= link_to("<i class='icon-plus-sign'></i> Account Info".html_safe,"#",:style => "float: left;font-size: 14px;height: 50px;line-height: 20px;padding: 15px;") %></li>
              <li><%= link_to("<i class='icon-off'></i> Logout".html_safe, destroy_user_session_path, :method => "delete", :data => {:confirm => "Are u sure want to logout?"}) %></li>
            </ul>
          </li>
        <% else %>
          <li class="dropdown " id="menuLogin">
            <%= link_to("Login", new_user_session_path, :class=> "dropdown-toggle ", :'data-toggle' => "dropdown") %>
            <div class="dropdown-menu popup_login">
              <%= simple_form_for(:user, url: user_session_path, :authenticity_token => true, :class=>"form-horizontal") do |f| %>
                <h3>Sign In</h3>
                  <%= f.input :email, required: false, placeholder: "email", label: false, autofocus: true, :class=>"input-large" %>
                  <%= f.input :password, required: false,label: false, placeholder: "password", :class=>"input-large" %>
                  <div class="clearfix"></div>
                  <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
                  <div class="clearfix"></div>
                  <%= f.button :submit, "Sign in", :class=>"btn btn-primary pull-right" %>
              <% end %>
            </div>
          </li>
          <li><%= link_to("Register", new_user_session_path) %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <%= yield %>
      </div>
    </div>
    <hr class="hr-normal">
    <footer>
      <p>
        <span style="text-align:left;float:left">&copy; 2014 <a href="http://bootstrapmaster.com" alt="Bootstrap Themes">creativeLabs</a></span>
        <span class="hidden-phone" style="text-align:right;float:right">Powered by: <a href="http://admintemplates.co" alt="Bootstrap Admin Templates">Integrated Analysis</a></span>
      </p>
    </footer>
  </div>
</body>

app/views/layouts/new_layout.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- start: Meta -->
  <meta charset="utf-8">
  <title>Integrated Analysis</title>
  <!-- start: Mobile Specific -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- end: Mobile Specific -->

  <!-- start: CSS -->
  <%= stylesheet_link_tag 'application' %>
  <!-- end: CSS -->
  <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
     <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <script src="assets/js/respond.min.js"></script>
    <script src="assets/css/ie6-8.css"></script>
  <![endif]-->

  <!-- start: Favicon and Touch Icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="http://localhost:8888/bootstrap/simpliq2/ico/apple-touch-icon-57-precomposed.png">
  <link rel="shortcut icon" href="http://localhost:8888/bootstrap/simpliq2/ico/favicon.png">
  <!-- end: Favicon and Touch Icons -->

</head>
<body>
  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>
</body>